# Generated by Django 3.1.7 on 2022-08-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttt', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
