# Generated by Django 3.1.7 on 2022-08-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttt', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
