# Generated by Django 3.1.7 on 2022-08-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttt', '0004_remove_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
